import { defineContentConfig, defineCollection, z } from "@nuxt/content";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

// Drafts must not just be hidden at query time: Nuxt Content ships a compressed
// dump of every collection row to the browser, so a draft's full body would be
// downloadable. Keep draft files out of the build unless previewing.
const showDrafts = process.env.NUXT_PUBLIC_SHOW_DRAFTS === 'true'
const draftBlogFiles = (): string[] => {
    if (showDrafts) return []
    const dir = join(process.cwd(), 'content', 'blog')
    try {
        return readdirSync(dir)
            .filter((f) => f.endsWith('.md'))
            .filter((f) => /^draft:\s*true\s*$/m.test(readFileSync(join(dir, f), 'utf8').match(/^---\n([\s\S]*?)\n---/)?.[1] ?? ''))
            .map((f) => `blog/${f}`)
    } catch {
        return []
    }
}
const draftExcludes = draftBlogFiles()

export default defineContentConfig({
    collections: {
        content: defineCollection({
            type: 'page',
            source: {
                include: '**/*.md',
                exclude: draftExcludes
            }
        }),
        blog: defineCollection({
            type: 'page',
            source: {
                include: 'blog/**/*.md',
                exclude: ['blog/index.md', ...draftExcludes],
                prefix: '/blog'
            },
            schema: z.object({
                tags: z.array(z.string()).optional(),
                title: z.string(),
                description: z.string(),
                created_at: z.date(),
                author: z.object({
                    name: z.string(),
                    description: z.string(),
                    image: z.string()
                }),
                projects: z.array(z.string()).optional(),
                // Drafts are hidden from listings and 404 on their own URL unless
                // runtimeConfig.public.showDrafts is on (NUXT_PUBLIC_SHOW_DRAFTS=true)
                draft: z.boolean().default(false)
            })
        }),
        photos: defineCollection({
            type: 'page',
            source: {
                include: 'photos/**/*.md',
                exclude: ['photos/index.md'],
                prefix: '/photos'
            },
            schema: z.object({
                title: z.string(),
                description: z.string(),
                src: z.string(),
                collections: z.array(z.string()).optional(),
                details: z.object({
                    DateTimeOriginal: z.string(),
                    Make: z.string(),
                    Model: z.string(),
                    ExposureBiasValue: z.number(),
                    FocalLength: z.number(),
                    ExposureTime: z.number(),
                    FNumber: z.number(),
                    ISOSpeedRatings: z.number(),
                    LensMake: z.string(),
                    LensModel: z.string(),
                })
            }),
        }),
        albums: defineCollection({
            type: 'page',
            source: {
                include: 'photos/**/*.md',
                exclude: ['photos/*.md'],
                prefix: '/albums'
            }
        }),
        projects: defineCollection({
            type: 'page',
            source: 'projects/**/*.md',
        }),
        // Generated by scripts/project-activity.mjs from local git history
        activity: defineCollection({
            type: 'data',
            source: 'project-activity/*.json',
            schema: z.object({
                slug: z.string(),
                repo: z.string(),
                generatedAt: z.string(),
                lastCommit: z.string(),
                totalCommits: z.number(),
                commitsLast90Days: z.number(),
                latestTag: z.string().nullable(),
                recent: z.array(z.object({
                    sha: z.string(),
                    date: z.string(),
                    subject: z.string()
                }))
            })
        }),
        about: defineCollection({
            type: 'page',
            source: 'about/**/*.md',
        }),
    }
})